In [1]:

# importing required libraries
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt
import numpy as np


# nltk libraries used for NLP
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
# from sklearn.feature_extraction.text import CountVectorizer
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LogisticRegression
# from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
# from sklearn.naive_bayes import MultinomialNB


In [26]:
df = pd.read_csv('../dataset/train_cleaned3.csv')
df.head()

id                                               name  \
0  22474  [ 'inform ' , 'regard ' , 'merger ' , 'navio '...   
1  27460  [ 'announc ' , 'approv ' , 'chang ' , 'members...   
2   6926  [ 'sfc ' , 'suspend ' , 'shiu ' , 'yau ' , 'wa...   
3   6982  [ 'renminbi ' , 'rmb ' , 'haircut ' , 'februar...   
4   5022  [ 'antimoney ' , 'launder ' , 'counter ' , 'fi...   

                                       document_text                  cat_name  
0  [ 'at ' , 'special ' , 'meet ' , 'held ' , 'ma...  Corporate Communications  
1  [ 'on ' , 'april ' , ' 2 ' , '2021 ' , 'china ...     Securities Settlement  
2  [ 'the ' , 'secur ' , 'futur ' , 'commiss ' , ...                 Antitrust  
3  [ 'pursuant ' , 'section ' , '262 ' , 'clear '...     Securities Settlement  
4  [ 'money ' , 'launder ' , 'terror ' , 'financ ...           Financial Crime

In [27]:
 df['name2'] = df['name'].apply(lambda x: x[1:-1])

In [28]:
df.head()

id                                               name  \
0  22474  [ 'inform ' , 'regard ' , 'merger ' , 'navio '...   
1  27460  [ 'announc ' , 'approv ' , 'chang ' , 'members...   
2   6926  [ 'sfc ' , 'suspend ' , 'shiu ' , 'yau ' , 'wa...   
3   6982  [ 'renminbi ' , 'rmb ' , 'haircut ' , 'februar...   
4   5022  [ 'antimoney ' , 'launder ' , 'counter ' , 'fi...   

                                       document_text  \
0  [ 'at ' , 'special ' , 'meet ' , 'held ' , 'ma...   
1  [ 'on ' , 'april ' , ' 2 ' , '2021 ' , 'china ...   
2  [ 'the ' , 'secur ' , 'futur ' , 'commiss ' , ...   
3  [ 'pursuant ' , 'section ' , '262 ' , 'clear '...   
4  [ 'money ' , 'launder ' , 'terror ' , 'financ ...   

                   cat_name                                              name2  
0  Corporate Communications   'inform ' , 'regard ' , 'merger ' , 'navio ' ...  
1     Securities Settlement   'announc ' , 'approv ' , 'chang ' , 'membersh...  
2                 Antitrust   'sfc ' , 'suspend ' , 'shiu ' , 'yau ' , 'wah...  
3     Securities Settlement   'renminbi ' , 'rmb ' , 'haircut ' , 'februari...  
4           Financial Crime   'antimoney ' , 'launder ' , 'counter ' , 'fin...

In [22]:
df['name'] = df['name'].apply(lambda x: ''.join(x))

In [23]:
df.head()

id                                               name  \
0  22474  [ 'inform ' , 'regard ' , 'merger ' , 'navio '...   
1  27460  [ 'announc ' , 'approv ' , 'chang ' , 'members...   
2   6926  [ 'sfc ' , 'suspend ' , 'shiu ' , 'yau ' , 'wa...   
3   6982  [ 'renminbi ' , 'rmb ' , 'haircut ' , 'februar...   
4   5022  [ 'antimoney ' , 'launder ' , 'counter ' , 'fi...   

                                       document_text                  cat_name  
0  [ 'at ' , 'special ' , 'meet ' , 'held ' , 'ma...  Corporate Communications  
1  [ 'on ' , 'april ' , ' 2 ' , '2021 ' , 'china ...     Securities Settlement  
2  [ 'the ' , 'secur ' , 'futur ' , 'commiss ' , ...                 Antitrust  
3  [ 'pursuant ' , 'section ' , '262 ' , 'clear '...     Securities Settlement  
4  [ 'money ' , 'launder ' , 'terror ' , 'financ ...           Financial Crime

id                                               name  \
0  22474  [ 'inform ' , 'regard ' , 'merger ' , 'navio '...   
1  27460  [ 'announc ' , 'approv ' , 'chang ' , 'members...   
2   6926  [ 'sfc ' , 'suspend ' , 'shiu ' , 'yau ' , 'wa...   
3   6982  [ 'renminbi ' , 'rmb ' , 'haircut ' , 'februar...   
4   5022  [ 'antimoney ' , 'launder ' , 'counter ' , 'fi...   

                                       document_text                  cat_name  
0  [ 'at ' , 'special ' , 'meet ' , 'held ' , 'ma...  Corporate Communications  
1  [ 'on ' , 'april ' , ' 2 ' , '2021 ' , 'china ...     Securities Settlement  
2  [ 'the ' , 'secur ' , 'futur ' , 'commiss ' , ...                 Antitrust  
3  [ 'pursuant ' , 'section ' , '262 ' , 'clear '...     Securities Settlement  
4  [ 'money ' , 'launder ' , 'terror ' , 'financ ...           Financial Crime

In [11]:
df['name'] = df['name'] + df['document_text']
df.drop(['document_text'], axis=1, inplace=True)

In [12]:
df.head()

id                                               name  \
0  22474  [   ' i n f o r m   '   ,   ' r e g a r d   ' ...   
1  27460  [   ' a n n o u n c   '   ,   ' a p p r o v   ...   
2   6926  [   ' s f c   '   ,   ' s u s p e n d   '   , ...   
3   6982  [   ' r e n m i n b i   '   ,   ' r m b   '   ...   
4   5022  [   ' a n t i m o n e y   '   ,   ' l a u n d ...   

                   cat_name  
0  Corporate Communications  
1     Securities Settlement  
2                 Antitrust  
3     Securities Settlement  
4           Financial Crime

In [53]:
X = df[['name']]
y = df['cat_name']

In [54]:
X.head()

name
0  [ 'inform ' , 'regard ' , 'merger ' , 'navio '...
1  [ 'announc ' , 'approv ' , 'chang ' , 'members...
2  [ 'sfc ' , 'suspend ' , 'shiu ' , 'yau ' , 'wa...
3  [ 'renminbi ' , 'rmb ' , 'haircut ' , 'februar...
4  [ 'antimoney ' , 'launder ' , 'counter ' , 'fi...

In [55]:
y

0            Corporate Communications
1               Securities Settlement
2                           Antitrust
3               Securities Settlement
4                     Financial Crime
                     ...             
47097            Corporate Governance
47098    Monetary and Economic Policy
47099                           Fraud
47100                      Exemptions
47101                Fees and Charges
Name: cat_name, Length: 47102, dtype: object

In [56]:
# train test split 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [57]:
# multiclass classification
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

# pipeline for multiclass classification
text_clf = Pipeline([
                        ('bow', CountVectorizer()),
                        ('tfidf', TfidfVectorizer()),
                        ('clf', OneVsRestClassifier(LinearSVC()))])
                

In [58]:
pipeline.fit(X_train['name'],y_train)

Pipeline(steps=[('bow', CountVectorizer()), ('tfidf', TfidfTransformer()),
                ('classifier', MultinomialNB())])

In [59]:
predictions = pipeline.predict(X_test['name'])

In [60]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
# print(classification_report(y_test,predictions))

In [61]:
print(confusion_matrix(y_test,predictions))

[[ 5  0  5 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0 11 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  1 ...  0  3  0]
 [ 0  0  0 ...  0  0  0]]


In [62]:
print(accuracy_score(y_test, predictions))

0.09595584332873368
